### PR TITLE
Added lexik_maintenance.response.exception_message parameter

### PR DESCRIPTION
**Pull request by tkuska**
Fixed dependency on non-existent parameter.

### CODE REVIEW

**Comment by leofeyer** [comment]
@spike31 The changes from #83 broke the bundle:



So can you please merge and release this PR?

**Comment by leofeyer** [comment]
Thank you.

**Comment by gilles-g** [comment]
Well I trust to fast on tests and PR :disappointed:

**Comment by leofeyer** [comment]
We all do, so don't be too hard on yourself. 😄

**Comment by rvanlaak** [comment]
Thanks all! Also did not catch this, did forgot that line.

**Pull request merged**
