### PR TITLE
Add compatibility of symfony 4

### PR DESCRIPTION
**Pull request by aivus**
Depends on #71 

#SymfonyConHackday2017

### CODE REVIEW

**Comment by spike31** [comment]
ping @aivus 
Could you try to fix conflict? if test are ok I will merge it.
Thanks :)

**Comment by aivus** [comment]
@spike31 I'll fix them in few days

**Comment by aivus** [comment]
@spike31 ready to review

**Comment by aivus** [comment]
@spike31 Symfony 4 introduces some changes related to new DI logic. 
At least related to the registering of commands.

I'll test and add changes if they will be required.

**Pull request merged**
