### PR TITLE
Add php 7.2 support

### PR DESCRIPTION
**Pull request by guillaume-sainthillier**
Cast $this-ips as array before to call count method

### CODE REVIEW

**Comment by leofeyer** [comment]
@spike31 The failing tests are actually not related to this change but to new deprecations in Symfony 3.4. Can you please consider merging this? Currently the bundle is not compatible with PHP 7.2.

**Comment by leofeyer** [comment]
Thank you. 👍

**Comment by aivus** [comment]
Hi @leofeyer 
> The failing tests are actually not related to this change but to new deprecations in Symfony 3.4.

It's actually a deprecation of php 7.2 and it will be great to find what causes it.

**Comment by spike31** [comment]
@aivus I think this is related to phpunit. Phpunit 5 is not still compatible with PHP 7.2

https://phpunit.de/

**Comment by spike31** [comment]
My previous comment was for the failling tests

**Pull request merged**
